Repository E24I/TOGEDOG, pull requests merged in 2023-12, with the labels that each got.

#113 :sparkles: feat: 피드 작성, 수정, 채팅 api 기능 로직 약간 수정
  client/src/components/chatting/ChattingLists.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.Style.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
  client/src/components/petFeed/writingSpace/WritingSpace.tsx
  client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.Style.tsx
  client/src/components/petFeed/writingSpace/updatingSpace/UpdatingSpace.tsx
  client/src/services/chatService.tsx
Labels: frontend, essential

#151 ✨ feat: profile 및 pet 도메인 구현
  server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
  server/src/main/java/togedog/server/domain/feed/repository/FeedRepository.java
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/dto/MemberDto.java
  server/src/main/java/togedog/server/domain/member/dto/MemberFeedDto.java
  server/src/main/java/togedog/server/domain/member/entity/Member.java
  server/src/main/java/togedog/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/togedog/server/domain/member/service/MemberService.java
  server/src/main/java/togedog/server/domain/pet/controller/PetController.java
  server/src/main/java/togedog/server/domain/pet/dto/PetDto.java
  server/src/main/java/togedog/server/domain/pet/entity/Pet.java
  server/src/main/java/togedog/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/togedog/server/domain/pet/repository/PetRepository.java
  server/src/main/java/togedog/server/domain/pet/service/PetService.java
  server/src/main/java/togedog/server/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/togedog/server/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/togedog/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/togedog/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/togedog/server/global/auth/utils/ErrorResponder.java
  server/src/main/java/togedog/server/global/auth/utils/ErrorResponse.java
  server/src/main/java/togedog/server/global/dto/MultiResponseDto.java
  server/src/main/java/togedog/server/global/exception/businessexception/petexception/PetException.java
  server/src/main/java/togedog/server/global/exception/businessexception/petexception/PetNotFoundException.java
  server/src/main/java/togedog/server/global/uri/UriCreator.java
  server/src/main/resources/application.yml
Labels: backend, high

#152 배포 수정본 12/12 11:28
  server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
  server/src/main/java/togedog/server/domain/feed/repository/FeedRepository.java
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/dto/MemberDto.java
  server/src/main/java/togedog/server/domain/member/dto/MemberFeedDto.java
  server/src/main/java/togedog/server/domain/member/entity/Member.java
  server/src/main/java/togedog/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/togedog/server/domain/member/service/MemberService.java
  server/src/main/java/togedog/server/domain/pet/controller/PetController.java
  server/src/main/java/togedog/server/domain/pet/dto/PetDto.java
  server/src/main/java/togedog/server/domain/pet/entity/Pet.java
  server/src/main/java/togedog/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/togedog/server/domain/pet/repository/PetRepository.java
  server/src/main/java/togedog/server/domain/pet/service/PetService.java
  server/src/main/java/togedog/server/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/togedog/server/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/togedog/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/togedog/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/togedog/server/global/auth/utils/ErrorResponder.java
  server/src/main/java/togedog/server/global/auth/utils/ErrorResponse.java
  server/src/main/java/togedog/server/global/dto/MultiResponseDto.java
  server/src/main/java/togedog/server/global/exception/businessexception/petexception/PetException.java
  server/src/main/java/togedog/server/global/exception/businessexception/petexception/PetNotFoundException.java
  server/src/main/java/togedog/server/global/uri/UriCreator.java
  server/src/main/resources/application.yml
Labels: backend, high

#171 12월17일 14:34분 배포
  server/src/main/java/togedog/server/domain/comment/controller/CommentController.java
  server/src/main/java/togedog/server/domain/comment/controller/dto/CommentReportApiRequest.java
  server/src/main/java/togedog/server/domain/comment/repository/CommentRepository.java
  server/src/main/java/togedog/server/domain/comment/service/CommentService.java
  server/src/main/java/togedog/server/domain/commentreport/entity/CommentReport.java
  server/src/main/java/togedog/server/domain/commentreport/repository/CommentReportRepository.java
  server/src/main/java/togedog/server/domain/commentreport/service/CommentReportService.java
  server/src/main/java/togedog/server/domain/commentreport/service/dto/request/CommentReportApiToService.java
  server/src/main/java/togedog/server/domain/commentreport/service/dto/response/CommentReportResponse.java
  server/src/main/java/togedog/server/domain/feed/controller/FeedController.java
  server/src/main/java/togedog/server/domain/feed/controller/dto/FeedReportApiRequest.java
  server/src/main/java/togedog/server/domain/feed/entity/Feed.java
  server/src/main/java/togedog/server/domain/feed/repository/FeedRepository.java
  server/src/main/java/togedog/server/domain/feed/service/FeedService.java
  server/src/main/java/togedog/server/domain/feed/service/dto/request/FeedReportApiToService.java
  server/src/main/java/togedog/server/domain/feedbookmark/service/FeedBookmarkService.java
  server/src/main/java/togedog/server/domain/feedlike/service/FeedLikeService.java
  server/src/main/java/togedog/server/domain/feedreport/entity/FeedReport.java
  server/src/main/java/togedog/server/domain/feedreport/repository/FeedReportRepository.java
  server/src/main/java/togedog/server/domain/feedreport/service/FeedReportService.java
  server/src/main/java/togedog/server/domain/feedreport/service/dto/response/FeedReportResponse.java
  server/src/main/java/togedog/server/domain/reply/controller/ReplyController.java
  server/src/main/java/togedog/server/domain/reply/controller/dto/ReplyReportApiRequest.java
  server/src/main/java/togedog/server/domain/reply/repository/ReplyRepository.java
  server/src/main/java/togedog/server/domain/reply/service/ReplyService.java
  server/src/main/java/togedog/server/domain/reply/service/dto/request/ReplyReportApiToService.java
  server/src/main/java/togedog/server/domain/replylike/service/ReplyLikeService.java
  server/src/main/java/togedog/server/domain/replyreport/entity/ReplyReport.java
  server/src/main/java/togedog/server/domain/replyreport/repository/ReplyReportRepository.java
  server/src/main/java/togedog/server/domain/replyreport/service/ReplyReportService.java
  server/src/main/java/togedog/server/domain/replyreport/service/dto/response/ReplyReportResponse.java
  server/src/main/java/togedog/server/global/entity/ReportState.java
  server/src/main/java/togedog/server/global/exception/businessexception/commentexception/CommentReportNotFoundException.java
  server/src/main/java/togedog/server/global/exception/businessexception/feedexception/FeedReportNotFoundException.java
  server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberRolesNotMatchException.java
  server/src/main/java/togedog/server/global/exception/businessexception/replyexception/ReplyReportNotFoundException.java
Labels: backend, high

#172 ✨ feat: Member 도메인 구현
  server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
  server/src/main/java/togedog/server/domain/feed/repository/FeedRepository.java
  server/src/main/java/togedog/server/domain/feedbookmark/repository/FeedBookmarkRepository.java
  server/src/main/java/togedog/server/domain/feedlike/repository/FeedLikeRepository.java
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/dto/MemberDto.java
  server/src/main/java/togedog/server/domain/member/entity/Member.java
  server/src/main/java/togedog/server/domain/member/repository/MemberRepository.java
  server/src/main/java/togedog/server/domain/member/service/MemberService.java
  server/src/main/java/togedog/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/togedog/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/togedog/server/global/exception/businessexception/dbexception/DbException.java
  server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberPasswordSameException.java
  server/src/main/java/togedog/server/global/mail/MailService.java
  server/src/main/resources/application.yml
  server/src/test/java/togedog/server/MemberControllerTest.java
  server/src/test/java/togedog/server/PasswordTest.java
Labels: backend, high

#173 2023.12.17 CICD
  server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
  server/src/main/java/togedog/server/domain/feed/repository/FeedRepository.java
  server/src/main/java/togedog/server/domain/feedbookmark/repository/FeedBookmarkRepository.java
  server/src/main/java/togedog/server/domain/feedlike/repository/FeedLikeRepository.java
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/dto/MemberDto.java
  server/src/main/java/togedog/server/domain/member/entity/Member.java
  server/src/main/java/togedog/server/domain/member/repository/MemberRepository.java
  server/src/main/java/togedog/server/domain/member/service/MemberService.java
  server/src/main/java/togedog/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/togedog/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/togedog/server/global/exception/businessexception/dbexception/DbException.java
  server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberPasswordSameException.java
  server/src/main/java/togedog/server/global/mail/MailService.java
  server/src/test/java/togedog/server/MemberControllerTest.java
Labels: backend, high

#176 비밀번호,닉네임,소개글 수정 완료 펫 추가 진행중
  client/src/App.tsx
  client/src/atoms.tsx
  client/src/atoms/atomsType.tsx
  client/src/atoms/imgForm/ImgForm.style.tsx
  client/src/atoms/imgForm/ImgForm.tsx
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/modal/Modal.tsx
  client/src/components/myPage/MyFeedForm.tsx
  client/src/components/myPage/MyInfoForm.tsx
  client/src/components/myPage/petComponent/PetList.tsx
  client/src/components/signUpElement/SignUpInputs.tsx
  client/src/components/userInfo/UserFeedForm.style.tsx
  client/src/components/userInfo/UserFeedForm.tsx
  client/src/components/userInfo/UserInfoForm.style.tsx
  client/src/components/userInfo/UserInfoForm.tsx
  client/src/components/userInfo/feedCardComponent/FeedCard.style.tsx
  client/src/components/userInfo/feedCardComponent/FeedCard.tsx
  client/src/components/userInfo/infoChangeComponent/PasswordChange.style.tsx
  client/src/components/userInfo/infoChangeComponent/PasswordChange.tsx
  client/src/components/userInfo/infoChangeComponent/ProfileChange.style.tsx
  client/src/components/userInfo/infoChangeComponent/ProfileChange.tsx
  client/src/components/userInfo/petComponent/ButtonDrop.style.tsx
  client/src/components/userInfo/petComponent/ButtonDrop.tsx
  client/src/components/userInfo/petComponent/PetAdd.style.tsx
  client/src/components/userInfo/petComponent/PetAddForm.tsx
  client/src/components/userInfo/petComponent/PetList.style.tsx
  client/src/components/userInfo/petComponent/PetList.tsx
  client/src/components/userInfo/petProfile/PetProfileForm.style.tsx
  client/src/components/userInfo/petProfile/PetProfileForm.tsx
  client/src/components/userInfo/petProfile/component/Category.style.tsx
  client/src/components/userInfo/petProfile/component/Category.tsx
  client/src/hooks/MemberHook.ts
  client/src/hooks/UserInfoHook.ts
  client/src/index.tsx
  client/src/pages/PetAdd.tsx
  client/src/pages/PetProfile.tsx
  client/src/pages/UserInfo.tsx
  client/src/services/myPageService.tsx
  client/src/services/userInfoService.tsx
  client/src/types/myPageType.tsx
  client/src/types/userInfoType.tsx
Labels: frontend

#183 ✨feat: 펫 수정 추가
  server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/pet/controller/PetController.java
  server/src/main/java/togedog/server/domain/pet/dto/PetDto.java
  server/src/main/java/togedog/server/domain/pet/entity/Pet.java
  server/src/main/java/togedog/server/domain/pet/mapper/PetMapper.java
  server/src/main/java/togedog/server/domain/pet/service/PetService.java
  server/src/main/java/togedog/server/global/exception/businessexception/petexception/PetMemberNotAccordException.java
  server/src/main/resources/application.yml
Labels: backend, high

#215 ✨ Feat : 회원 이미지 변경/삭제, Member검색 구현
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/dto/MemberDto.java
  server/src/main/java/togedog/server/domain/member/repository/MemberRepository.java
  server/src/main/java/togedog/server/domain/member/service/MemberService.java
  server/src/main/java/togedog/server/domain/pet/controller/PetController.java
  server/src/main/resources/application.yml
Labels: backend
