Repository E24I/TOGEDOG, pull requests merged in 2023-11, with the labels that each got.

#10 [BE] 도메인별 Entity Column 작성
  server/src/main/java/togedog/server/domain/alarm/entity/Alarm.java
  server/src/main/java/togedog/server/domain/alram/entity/Alram.java
  server/src/main/java/togedog/server/domain/chatreport/entity/ChatReport.java
  server/src/main/java/togedog/server/domain/chatroom/entity/ChatRoom.java
  server/src/main/java/togedog/server/domain/comment/entity/Comment.java
  server/src/main/java/togedog/server/domain/commentreport/entity/CommentReport.java
  server/src/main/java/togedog/server/domain/feed/entity/Feed.java
  server/src/main/java/togedog/server/domain/feedlike/entity/FeedLike.java
  server/src/main/java/togedog/server/domain/join/entity/Join.java
  server/src/main/java/togedog/server/domain/member/entity/Member.java
  server/src/main/java/togedog/server/domain/member/entity/Role.java
  server/src/main/java/togedog/server/domain/memberreport/entity/MemberReport.java
  server/src/main/java/togedog/server/domain/message/entity/Message.java
  server/src/main/java/togedog/server/domain/pet/entity/Gender.java
  server/src/main/java/togedog/server/domain/pet/entity/Pet.java
  server/src/main/java/togedog/server/domain/reply/entity/Reply.java
  server/src/main/java/togedog/server/domain/replylike/entity/ReplyLike.java
  server/src/main/java/togedog/server/domain/replyreport/entity/ReplyReport.java
  server/src/main/java/togedog/server/global/entity/BaseEnum.java
  server/src/main/java/togedog/server/global/entity/State.java
  server/src/main/java/togedog/server/global/entity/UserState.java
  server/src/test/java/togedog/server/ServerApplicationTests.java
Labels: backend

#18 ✨ : svg 아이콘 추가, 피드 리스트 div 틀 생성
  client/src/App.tsx
  client/src/assets/images/icons/BookMark.svg
  client/src/assets/images/icons/Dots.svg
  client/src/assets/images/icons/Heart.svg
  client/src/assets/images/icons/ImageCover.svg
  client/src/assets/images/icons/LeftArrow.svg
  client/src/assets/images/icons/Person.svg
  client/src/assets/images/icons/Pets.svg
  client/src/assets/images/icons/PinMark.svg
  client/src/assets/images/icons/RightArrow.svg
  client/src/components/header/Header.tsx
  client/src/components/petFeed/FeedDummy.tsx
  client/src/components/petFeed/FeedList.tsx
  client/src/index.css
  client/src/pages/PetFeed.tsx
  client/src/services/feedService.tsx
  client/src/types/feedDataType.tsx
Labels: frontend, low, essential

#20 :sparkles: feat 로그인,회원가입 프레임 작업중
  client/src/App.tsx
  client/src/assets/images/icons/GoogleIcon.svg
  client/src/assets/images/icons/KakaoIcon.svg
  client/src/assets/images/icons/NaverIcon.svg
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/loginElement/Oauth.tsx
  client/src/pages/Login.tsx
Labels: low

#28 ✨ : 서버 application yml 파일 분리 + 연관관계 매핑
  server/.gitignore
  server/src/docs/asciidoc/member.adoc
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/entity/Member.java
  server/src/main/java/togedog/server/domain/memberreport/entity/MemberReport.java
  server/src/main/java/togedog/server/domain/pet/entity/Gender.java
  server/src/main/java/togedog/server/domain/pet/entity/Pet.java
  server/src/main/resources/application-prod.yml
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
  server/src/test/java/togedog/server/MemberControllerTest.java
  server/src/test/java/togedog/server/ServerApplicationTests.java
Labels: backend, essential

#35 ✨ : build.gradle 수정(mapstruct, validation추가)
  server/build.gradle
  server/src/main/java/togedog/server/domain/member/dto/MemberDto.java
Labels: backend

#37 ✨ feat : MemberDto 에러 수정
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/dto/MemberDto.java
  server/src/main/java/togedog/server/domain/member/entity/Member.java
  server/src/main/java/togedog/server/domain/replylike/entity/ReplyLike.java
Labels: backend

#40 :recycle:refactor: input=>react-hook-form 변경
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/loginElement/Oauth.tsx
  client/src/components/signUpElement/SignUpForm.tsx
  client/src/components/signUpElement/SignUpInputs.tsx
  client/src/pages/SignUp.tsx
Labels: midium

#43 ✨ 이메일기능 추가
  server/build.gradle
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/service/MemberService.java
  server/src/main/java/togedog/server/global/mail/EmailConfig.java
  server/src/main/java/togedog/server/global/mail/MailService.java
  server/src/main/resources/application.yml
Labels: backend

#45 :sparkles:feat:로그인,회원가입 스타일파일분리
  client/src/App.tsx
  client/src/components/loginElement/LoginForm.style.tsx
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/loginElement/Oauth.style.tsx
  client/src/components/loginElement/Oauth.tsx
  client/src/components/myPage/MyFeedForm.tsx
  client/src/components/myPage/MyInfoForm.tsx
  client/src/components/signUpElement/SignUpForm.style.tsx
  client/src/components/signUpElement/SignUpForm.tsx
  client/src/components/signUpElement/SignUpInputs.style.tsx
  client/src/components/signUpElement/SignUpInputs.tsx
  client/src/pages/MyPage.tsx
Labels: frontend

#48 ✨feat: Chat 패키지 수정 및 Socket Config 추가
  server/src/main/java/togedog/server/domain/chat/config/WebSocketConfig.java
  server/src/main/java/togedog/server/domain/chat/controller/ChatController.java
  server/src/main/java/togedog/server/domain/chat/controller/MessageController.java
  server/src/main/java/togedog/server/domain/chat/dto/ChatPostRequest.java
  server/src/main/java/togedog/server/domain/chat/dto/MessageRequest.java
  server/src/main/java/togedog/server/domain/chat/entity/ChatParticipant.java
  server/src/main/java/togedog/server/domain/chat/entity/ChatRoom.java
  server/src/main/java/togedog/server/domain/chat/entity/Message.java
  server/src/main/java/togedog/server/domain/chat/service/ChatService.java
  server/src/main/java/togedog/server/domain/chatreport/entity/ChatReport.java
  server/src/main/java/togedog/server/domain/mapcontent/entity/MapContent.java
  server/src/main/java/togedog/server/domain/mapcontentbookmark/entity/MapContentBookmark.java
  server/src/main/java/togedog/server/domain/mapcontentlike/entity/MapContentLike.java
Labels: backend

#52 :sparkles:마이페이지 프레임작업중
  client/src/components/myPage/MyFeedForm.style.tsx
  client/src/components/myPage/MyFeedForm.tsx
  client/src/components/myPage/MyInfoForm.style.tsx
  client/src/components/myPage/MyInfoForm.tsx
  client/src/components/signUpElement/SignUpForm.style.tsx
  client/src/components/signUpElement/SignUpForm.tsx
  client/src/components/signUpElement/SignUpInputs.style.tsx
  client/src/components/signUpElement/SignUpInputs.tsx
  client/src/pages/MyPage.tsx
Labels: frontend

#56 ✨ 시큐리티 및 Member 도메인 구성
  .github/workflows/main.yml
  .gitignore
  server/build.gradle
  server/src/main/generated/togedog/server/domain/member/mapper/MemberMapperImpl.java
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/togedog/server/domain/member/repository/MemberRepository.java
  server/src/main/java/togedog/server/domain/member/service/MemberService.java
  server/src/main/java/togedog/server/global/auth/config/SecurityConfig.java
  server/src/main/java/togedog/server/global/auth/details/MemberDetailsService.java
  server/src/main/java/togedog/server/global/auth/dto/LoginDto.java
  server/src/main/java/togedog/server/global/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/togedog/server/global/dto/MultiResponseDto.java
  server/src/main/java/togedog/server/global/dto/PageInfo.java
  server/src/main/java/togedog/server/global/dto/SingleResponseDto.java
  server/src/main/java/togedog/server/global/mail/MailService.java
  server/src/main/java/togedog/server/global/mail/dto/EmailCheckDto.java
  server/src/main/java/togedog/server/global/redis/RedisUtil.java
  server/src/main/resources/application-dev.yml
Labels: backend

#71 :sparkles: : 헤더 모달 추가 및 라우팅, 알림 팝업 프레임 목업, 지도api 통신 연결
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/proxyserver/package-lock.json
  client/proxyserver/package.json
  client/proxyserver/server.js
  client/src/.env
  client/src/assets/images/icons/headerIcons/Alarm.svg
  client/src/assets/images/icons/headerIcons/Chat.svg
  client/src/assets/images/icons/headerIcons/Logout.svg
  client/src/assets/images/icons/headerIcons/Mode.svg
  client/src/assets/images/icons/headerIcons/Mypage.svg
  client/src/assets/images/icons/headerIcons/Search.svg
  client/src/components/alarm/Alarm.Style.tsx
  client/src/components/alarm/Alarm.tsx
  client/src/components/chatting/ChattingContent.tsx
  client/src/components/chatting/ChattingListForm.tsx
  client/src/components/header/Header.Style.tsx
  client/src/components/header/Header.tsx
  client/src/components/modal/Modal.Style.tsx
  client/src/components/modal/Modal.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
  client/src/components/toast/Toast.Style.tsx
  client/src/components/toast/Toast.tsx
  client/src/index.tsx
  client/src/proxy/setUpProxy.tsx
  client/src/services/MapSearchingService.tsx
  client/src/services/Service.tsx
  client/tsconfig.json
Labels: frontend, essential

#68 ✨feat: global 공통화 및 feed CRUD 추가
  .idea/aws.xml
  .idea/misc.xml
  server/src/main/java/togedog/server/domain/comment/Controller/dto/CommentCreateApiRequest.java
  server/src/main/java/togedog/server/domain/comment/repository/CommentRepository.java
  server/src/main/java/togedog/server/domain/comment/service/CommentService.java
  server/src/main/java/togedog/server/domain/comment/service/dto/CommentCreateServiceRequest.java
  server/src/main/java/togedog/server/domain/feed/controller/FeedController.java
  server/src/main/java/togedog/server/domain/feed/controller/dto/FeedCreateApiRequest.java
  server/src/main/java/togedog/server/domain/feed/controller/dto/FeedUpdateApiRequest.java
  server/src/main/java/togedog/server/domain/feed/entity/Feed.java
  server/src/main/java/togedog/server/domain/feed/repository/FeedRepository.java
  server/src/main/java/togedog/server/domain/feed/service/FeedService.java
  server/src/main/java/togedog/server/domain/feed/service/dto/request/FeedCreateServiceApiRequest.java
  server/src/main/java/togedog/server/domain/feed/service/dto/request/FeedUpdateServiceRequest.java
  server/src/main/java/togedog/server/domain/feed/service/dto/response/FeedResponse.java
  server/src/main/java/togedog/server/domain/feedlike/repository/FeedLikeRepository.java
  server/src/main/java/togedog/server/domain/feedlike/service/FeedLikeService.java
  server/src/main/java/togedog/server/domain/member/mapper/MemberInfo.java
  server/src/main/java/togedog/server/domain/reply/controller/ReplyController.java
  server/src/main/java/togedog/server/domain/reply/repository/ReplyRepository.java
  server/src/main/java/togedog/server/domain/reply/service/ReplyService.java
  server/src/main/java/togedog/server/global/exception/businessexception/BusinessException.java
  server/src/main/java/togedog/server/global/exception/businessexception/feedexception/FeedException.java
  server/src/main/java/togedog/server/global/exception/businessexception/feedexception/FeedNotFoundException.java
  server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberAccessDeniedException.java
  server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberException.java
  server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberNotFoundException.java
  server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberNotLoginException.java
  server/src/main/java/togedog/server/global/exception/businessexception/replyexception/ReplyException.java
  server/src/main/java/togedog/server/global/exception/businessexception/replyexception/ReplyNotFoundException.java
  server/src/main/java/togedog/server/global/exception/businessexception/requestexception/RequestContentTypeException.java
  server/src/main/java/togedog/server/global/exception/businessexception/requestexception/RequestException.java
  server/src/main/java/togedog/server/global/exception/businessexception/requestexception/RequestTypeException.java
  server/src/main/java/togedog/server/global/exception/exceptionhandler/RestControllerAdvice.java
  server/src/main/java/togedog/server/global/response/ApiPageResponse.java
  server/src/main/java/togedog/server/global/response/ApiSingleResponse.java
  server/src/main/java/togedog/server/global/response/PageInformation.java
  server/src/main/resources/application.yml
Labels: backend, high

#82 :sparkles:마이페이지 수정모달추가,피드리스트 생성
  client/src/assets/images/icons/Feeds.svg
  client/src/assets/images/icons/Heart.svg
  client/src/components/common/DropDown.Style.tsx
  client/src/components/common/DropDown.tsx
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/myPage/MyFeedForm.style.tsx
  client/src/components/myPage/MyFeedForm.tsx
  client/src/components/myPage/MyInfoForm.tsx
  client/src/components/myPage/feedCardComponent/FeedCard.style.tsx
  client/src/components/myPage/feedCardComponent/FeedCard.tsx
  client/src/components/myPage/infoChangeComponent/PasswordChange.style.tsx
  client/src/components/myPage/infoChangeComponent/PasswordChange.tsx
  client/src/components/myPage/infoChangeComponent/ProfileChange.style.tsx
  client/src/components/myPage/infoChangeComponent/ProfileChange.tsx
  client/src/components/myPage/petComponent/PetList.style.tsx
  client/src/components/toast/DropDown.Style.tsx
  client/src/components/toast/DropDown.tsx
Labels: frontend

#80 :sparkles: feat: 피드 작성 페이지 맵 연결
  client/package-lock.json
  client/package.json
  client/proxyserver/package-lock.json
  client/proxyserver/package.json
  client/proxyserver/server.js
  client/public/index.html
  client/src/assets/images/icons/Marker.svg
  client/src/components/chatting/ChattingContent.tsx
  client/src/components/chatting/ChattingListForm.tsx
  client/src/components/common/DropDown.Style.tsx
  client/src/components/common/DropDown.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/Map.Style.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/Map.tsx
  client/src/components/petFeed/writingSpace/WritingSpace.tsx
  client/src/components/petFeed/writingSpace/WritingSpaces.Style.tsx
  client/src/services/MapSearchingService.tsx
  client/src/types/feedDataType.tsx
  client/src/types/sgis.d.ts
  client/tsconfig.json
Labels: frontend, high, essential

#88 :sparkles:로그인,회원가입 버튼기능 구현중
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/signUpElement/SignUpInputs.tsx
Labels: frontend

#85 ✨ feat: 피드 작성 첨부파일 기능 수정중
  client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/Map.Style.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/Map.tsx
  client/src/components/petFeed/writingSpace/Map.Style.tsx
  client/src/components/petFeed/writingSpace/Map.tsx
  client/src/components/petFeed/writingSpace/WritingSpace.tsx
  client/src/components/petFeed/writingSpace/WritingSpaces.Style.tsx
  client/src/services/feedService.tsx
  client/src/types/feedDataType.tsx
  client/src/types/sgis.d.ts
Labels: frontend, high, essential

#97 :sparkles: presinedUrl, chatting
  client/package-lock.json
  client/package.json
  client/src/components/chatting/ChattingContent.tsx
  client/src/components/chatting/ChattingListForm.Style.tsx
  client/src/components/chatting/ChattingListForm.tsx
  client/src/components/chatting/ChattingLists.tsx
  client/src/components/chatting/ContentListForm.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.Style.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/CreatingSpace.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/Upload.Style.tsx
  client/src/components/petFeed/writingSpace/CreatingSpace/Upload.tsx
  client/src/components/petFeed/writingSpace/Map.tsx
  client/src/components/petFeed/writingSpace/WritingSpace.tsx
  client/src/services/chatService.tsx
  client/src/services/feedService.tsx
  client/src/types/feedDataType.tsx
Labels: frontend, essential

#98 :building_construction: axios 통신 폴더분리
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/signUpElement/SignUpInputs.style.tsx
  client/src/components/signUpElement/SignUpInputs.tsx
  client/src/services/loginService.tsx
  client/src/services/signUpService.tsx
Labels: frontend

#102 :sparkles: feat: stompjs connecting
  client/src/components/chatting/ChattingContent.tsx
  client/src/components/chatting/ChattingDetail.Style.tsx
  client/src/components/chatting/ChattingDetail.tsx
  client/src/components/chatting/ChattingListForm.Style.tsx
  client/src/components/chatting/ChattingListForm.tsx
  client/src/components/chatting/ChattingLists.Style.tsx
  client/src/components/chatting/ChattingLists.tsx
  client/src/components/chatting/ContentListForm.tsx
  client/src/components/chatting/DetailForm.Style.tsx
  client/src/components/chatting/DetailForm.tsx
  client/src/pages/Chatting.tsx
  client/src/services/chatService.tsx
Labels: frontend, essential

#107 :sparkles:recoil 추가,로그인 서비스 토큰 저장 로직추가
  client/src/App.tsx
  client/src/atoms.tsx
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/myPage/MyInfoForm.style.tsx
  client/src/components/myPage/petProfile/component/Category.style.tsx
  client/src/components/myPage/petProfile/component/Category.tsx
  client/src/services/loginService.tsx
  client/src/services/myPageService.tsx
  client/src/types/myPageType.tsx
Labels: frontend

#108 ✨feat: LoginMemberUtil수정, refresh토큰삭제, SecurityConfig추가(주석처리), Exception추가
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/domain/member/service/MemberService.java
  server/src/main/java/togedog/server/global/auth/config/SecurityConfig.java
  server/src/main/java/togedog/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/togedog/server/global/auth/utils/LoginMemberUtil.java
  server/src/main/java/togedog/server/global/exception/businessexception/memberexception/MemberExistException.java
  server/src/main/resources/application.yml
Labels: backend, high

#111 ✨ feat: JPA Auditing 추가
  server/src/main/java/togedog/server/ServerApplication.java
  server/src/main/java/togedog/server/domain/member/controller/MemberController.java
  server/src/main/java/togedog/server/global/auth/filter/JwtAuthenticationFilter.java
Labels: backend, high

#109 :bug:회원가입,로그인 오류 수정, 로컬스토리지 토큰저장완료
  client/src/components/loginElement/LoginForm.tsx
  client/src/components/signUpElement/SignUpInputs.tsx
  client/src/services/loginService.tsx
  client/src/services/signUpService.tsx
Labels: frontend
